language: php
php:
  - '7.1'
  - '7.2'
  - '7.3'

sudo: false
matrix:
  allow_failures:
    - php: '7.1'
before_install:
  - sudo apt-get update
  - echo "extension=mongodb.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
install:
  - composer install --no-interaction --prefer-source
script:
  - make tests_all